import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.css";
import fonts, { defaultFont } from "../fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LocaleLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={locale}>
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
            </head>
            <body style={defaultFont.style}>{children}</body>
        </html>
    );
}
